// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuwlgfesqgjuymkwbcdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1d2xnZmVzcWdqdXlta3diY2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDQ3MjgsImV4cCI6MjA1OTc4MDcyOH0.BJjJyDITi9swHgYmgFTIuM95Ov7Mz5Ta1asSDrMfe7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);